### PR TITLE
Add name attribute

### PR DESCRIPTION
**Pull request by adrianmoisey**
Partial fix for: https://github.com/yola/chef/issues/1322

### CODE REVIEW

**Comment by bearnard** [comment]
:+1:

**Comment by sweetlikepete** [comment]
:+1:

**Comment by sweetlikepete** [comment]
is this awkies?

**Comment by adrianmoisey** [comment]
lol

**Comment by zoidbergwill** [comment]
HEY PETE! o/

**Comment by sweetlikepete** [comment]
waddup will friend!

**Comment by adrianmoisey** [comment]
Thanks for the thumb Pete!

**Comment by adrianmoisey** [comment]
staff

**Comment by sweetlikepete** [comment]
:+1: :+1: :+1: :+1:

**Comment by zoidbergwill** [comment]
:<

**Comment by sweetlikepete** [comment]
?

**Comment by zoidbergwill** [comment]
Why aren't you coming for lunch?

**Comment by sweetlikepete** [comment]
gotta move house - was the only slot I could get movers for - soz friend Will

**Pull request merged**
